language: ruby
cache:
  directories:
    - node_modules
    - /home/travis/.rvm/gems
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
  - nvm install 7
  - gem install bundler
  - npm install -g yarn
rvm:
  - 2.2.2
install:
  - bundle
  - rake db:create db:migrate db:seed
  - yarn
  - yarn build
script:
  - rake test
