language: ruby
cache:
  yarn: true
  bundler: true
  directories:
    - node_modules
    - gems
before_install:
  - nvm install 7
  - gem install bundler
  - npm install -g yarn
rvm:
  - 2.2.2
install:
  - bundle
  - rake db:create db:migrate db:seed
  - yarn
  - yarn build
script:
  - rake test
