apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: db
  namespace: obeder
spec:
  replicas: 1
  template:
    metadata:
      name: db
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres
        env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
          - name: db-files
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-files
        persistentVolumeClaim:
          claimName: db
