apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: obeder
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config
            mountPath: /etc/nginx/sites-available/
      volumes:
        - name: config
          configMap:
            name: nginx
