apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: obeder
data:
  default: |
    upstream puma {
      server web:3000;
    }

    server {
      listen 80;
      root /root/apps/obeder/current/public;
      access_log /var/log/nginx/obeder_access.log;
      error_log /var/log/nginx/obeder_error.log;

      location @obeder {
        proxy_http_version 1.1;
        proxy_pass http://puma;
        proxy_set_header       Host            $host;
        proxy_set_header       X-Real-IP       $remote_addr;
        proxy_set_header       X-Forwarded-For $remote_addr;
        proxy_redirect         off;
      }

      location / {
        try_files $uri @obeder;
      }
    }
