apiVersion: v1
kind: ConfigMap
metadata:
  name: web
  namespace: obeder
data:
  nginx: |
    upstream puma {
      server web:3000;
    }

    server {
      listen 80;
      root /static;

      location @obeder {
        proxy_http_version 1.1;
        proxy_pass http://puma;
        proxy_set_header       Host            $host;
        proxy_set_header       X-Real-IP       $remote_addr;
        proxy_set_header       X-Forwarded-For $remote_addr;
        proxy_redirect         off;
      }

      location / {
        try_files $uri @obeder;
      }
    }
